name: Update GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight
  workflow_dispatch:      # allows manual run

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: matchai/github-readme-stats-action@v1
        with:
          username: fawkeso16
          github_token: ${{ secrets.GH_TOKEN }}
          theme: tokyonight
          count_private: true
          output_path: stats
