name: Update GitHub Stats

# Triggers:
# 1. Manual run from Actions tab (workflow_dispatch)
# 2. On every push to main (ensures the workflow shows up quickly and updates stats if code changes)
# 3. Daily scheduled run at 00:00 UTC
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"  # daily at 00:00 UTC

# Needed so the workflow can push the generated stats file back.
permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Metrics (includes private if token scoped)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }} # PAT with repo scope to include private contributions
          user: fawkeso16
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Etc/UTC
          filename: stats/metrics.svg
          config_display: large
          plugins_errors_fatal: false
          # Add plugins below as desired (examples commented):
          # plugin_languages: yes
          # plugin_languages_ignored: html, css
          # plugin_languages_details: bytes-size, percentage
          # plugin_followup: yes
          # plugin_followup_sections: repositories, user
          # plugin_lines: yes

      - name: Commit and push updated stats (if changed)
        run: |
          if git diff --quiet --exit-code; then
            echo "No changes to commit"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats
          git commit -m "chore: update stats $(date -u +'%Y-%m-%d')"
          git push

      - name: Upload stats artifact (optional visibility)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stats-output
          path: stats

# Notes:
