name: Update GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate stats
        uses: anuraghazra/github-readme-stats@v0.3.6
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          username: fawkeso16
          theme: tokyonight
          show_icons: true
          count_private: true
